name: Run Tests
run-name: ${{ github.actor }} is running tests
on: [push, pull_request]
jobs:
  Validate-Changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Cache dependencies
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      - run: npm run eslint-check
      - run: npm run prettier-check
